name: Stdlib Release

on: [ workflow_dispatch ]
jobs:
    build:
        name: Release Ballerina Stdlibs
        runs-on: ubuntu-latest
        if: github.repository_owner == 'ballerina-platform'
        steps:
            -   uses: actions/checkout@v2

            -   name: Release Ballerina Libraries
                uses: ballerina-platform/ballerina-action@2201.8.6
                with:
                    args:
                        run
                env:
                    WORKING_DIR: ./release
                    BALLERINA_BOT_TOKEN: ${{ secrets.BALLERINA_BOT_TOKEN }}
