name: Trivy

on:
  workflow_call:
    inputs:
      hana-connector-group:
        required: true
        type: string

jobs:
  ubuntu-build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17.0.7

      - name: Build with Gradle
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
        run: ./gradlew build -x test -x :${{ inputs.hana-connector-group }}-examples:build -x:${{ inputs.hana-connector-group }}-sanitations:build 

      - name: Create lib Directory if not Exists
        run: |
          cd ballerina
          for dir in $(find . -type d -maxdepth 1  -mindepth 1); do
            if [[ "$dir" == *resources ]]; then
              continue
            fi
            (cd "$dir" && mkdir -p lib && cd ..); 
          done

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: "rootfs"
          scan-ref: "/github/workspace/ballerina/**/lib"
          format: "table"
          timeout: "10m0s"
          exit-code: "1"
