name: Test Ballerina Library Releases with Staging Central

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Branch/Release Tag(v2201.1.0) of the distribution
        required: true
        default: master

jobs:
  test-patch-versions:
    name: Test Patch Ballerina Library Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: 'ballerina-platform/ballerina-distribution'
          ref: ${{github.event.inputs.tag}}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17.0.7

      - name: Run Ballerina library Tests
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
        run: ./gradlew clean testStdlibs --stacktrace --scan --console=plain --no-daemon --continue

      - name: Run Ballerina Library Tests w/ Staging
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
        run: ./gradlew testStdlibsWithStaging --stacktrace --scan --console=plain --no-daemon --continue

  test-minor-versions:
    name: Test Minor Ballerina Library Releases
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: 'ballerina-platform/ballerina-distribution'
          ref: ${{github.event.inputs.tag}}

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17.0.7

      - name: Run Ballerina Library Tests
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
        run: ./gradlew clean testStdlibs --stacktrace --scan --console=plain --no-daemon --continue

      - name: Run Ballerina Library Tests w/ Staging
        env:
          packageUser: ${{ github.actor }}
          packagePAT: ${{ secrets.GITHUB_TOKEN }}
          devCentralToken: ${{ secrets.BALLERINA_DEV_CENTRAL_ACCESS_TOKEN }}
        run: ./gradlew testStdlibsWithStaging -PtestMinorVersionDifference --stacktrace --scan --console=plain --no-daemon --continue
